name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongodb:
        image: mongo:6
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo_test_user
          MONGO_INITDB_ROOT_PASSWORD: mongo_test_pass
          MONGO_INITDB_DATABASE: test_db
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests Only
        run: |
          mvn clean test \
            -Dspring.datasource.url=jdbc:postgresql://localhost:5432/testdb \
            -Dspring.datasource.username=testuser \
            -Dspring.datasource.password=testpass \
            -Dspring.data.mongodb.uri=mongodb://mongo_test_user:mongo_test_pass@localhost:27017/test_db?authSource=admin \
            -DskipITs=true
        env:
          SPRING_PROFILES_ACTIVE: test
          MONGO_PASSWORD: mongo_test_pass
          MAIL_ADDRESS_USERNAME: test@email.test
          MAIL_APP_PASSWORD: test_password
          APP_BASE_URL: http://localhost:8080
          ADMIN_EMAIL: admin@mail.com
          ADMIN_PASSWORD: admin_pass
          ADMIN_NAME: admin
          JWT_SECRET: test_jwt_secret
          JWT_EXP: 50000
          JWT_REFRESH_EXP: 150000
          OTP_EXP: 600
          OTP_LENGTH: 6
          ALLOWED_ORIGINS: "*"

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/
          retention-days: 7

  # Build and Push Docker Image
  build-push:
    runs-on: ubuntu-latest
    needs: build-test
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate next version
        id: version
        run: |
          # Get current version from file (or start with 1.0.0)
          if [ -f .version ]; then
          CURRENT_VERSION=$(cat .version)
          else
          CURRENT_VERSION="1.0.0"
          fi

          # Parse version components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Auto-increment patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          # Save new version
          echo "$NEW_VERSION" > .version

          # Output for GitHub Actions
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

          echo "✅ Version incremented: $CURRENT_VERSION → $NEW_VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with version tags
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            anonto/hrms-backend:latest
            anonto/hrms-backend:${{ env.VERSION }}
            anonto/hrms-backend:${{ github.sha }}
          labels: |
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Generate deployment payload
        run: |
          echo "IMAGE_TAG=anonto/hrms-backend:${{ env.VERSION }}" >> $GITHUB_ENV
          echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Output image info
        run: |
          echo "🎯 Version: ${{ env.VERSION }}"
          echo "📦 Image tags:"
          echo "   - anonto/hrms-backend:latest"
          echo "   - anonto/hrms-backend:${{ env.VERSION }}"
          echo "   - anonto/hrms-backend:${{ github.sha }}"
          echo "✅ Image pushed to Docker Hub"

  # Deploy to vps
  deploy-production:
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: IMAGE_TAG
          script: |
            # Update the .env file with new image tag
            cd ~/hrms-deployment

            # Run deployment script
            echo "🚀 Executing deployment script..."
            ./deploy.sh